In [1]:
#Task 1
import pandas as pd

url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [2]:
#Task 2
# Replace missing values in 'Min.Price' and 'Max.Price'
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [3]:
#Task 3
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtered_df = df[df.sum(axis=1) > 100]
print(filtered_df)

     0   1   2   3
0   20  32  37  28
1   32  34  12  36
5   32  16  32  25
6   30  30  24  23
9   30  22  15  38
12  34  25  34  36
13  35  30  37  15


In [4]:
#Task 4
original_array = np.random.randint(1, 100, size=(4, 4))

rows_array = original_array
columns_array = original_array.T
sum_rows = lambda array: np.sum(array, axis=1)
sum_columns = lambda array: np.sum(array, axis=0)

row_sums = sum_rows(rows_array)
column_sums = sum_columns(columns_array)
original_array, row_sums, column_sums

(array([[10, 87, 77, 41],
        [51, 56, 12, 22],
        [61, 39, 61, 40],
        [62, 61, 88, 43]]),
 array([215, 141, 201, 254]),
 array([215, 141, 201, 254]))